# Generated by Django 3.2 on 2021-05-06 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCourses',
            fields=[
                ('kurs', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kurs_name', models.CharField(max_length=100)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='name', max_length=254)),
                ('bdate', models.DateField()),
                ('coffee_address', models.TextField()),
                ('number', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.user'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('news_text', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('kurs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.rolecourses')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
    ]
