# Generated by Django 3.1.7 on 2021-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=150, verbose_name='Продукт')),
                ('price', models.PositiveIntegerField(help_text='указывать сумму в рублях', verbose_name='Цена')),
                ('squirrels', models.PositiveIntegerField(verbose_name='Белки')),
                ('fats', models.PositiveIntegerField(verbose_name='Жиры')),
                ('carbohydrates', models.PositiveIntegerField(verbose_name='Каброгидраты')),
                ('description_of_food', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('image', models.ImageField(blank=True, upload_to='main/img/%Y/%m/%d/', verbose_name='Изображение продукта')),
            ],
        ),
    ]
