# Generated by Django 3.1.7 on 2021-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/main/img/aboutproduct/%Y/%m/%d/', verbose_name='Изображение продукта'),
        ),
    ]
