# Generated by Django 3.1.7 on 2021-05-12 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210510_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCourses',
            fields=[
                ('kurs', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kurs_name', models.CharField(max_length=100)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutproduct',
            options={'verbose_name': 'О продукте', 'verbose_name_plural': 'О продуктах'},
        ),
        migrations.AlterField(
            model_name='aboutproduct',
            name='description_of_food',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/main/img/aboutproduct/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='static/main/img/users/%Y/%m/%d/', verbose_name='Изображение')),
                ('bdate', models.DateField()),
                ('coffee_address', models.TextField()),
                ('number', models.CharField(blank=True, max_length=11)),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('news_text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='static/main/img/news/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('kurs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.rolecourses')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
    ]
