# Generated by Django 3.1.7 on 2021-05-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210513_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
