# Generated by Django 3.1.7 on 2021-05-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolecourses',
            name='role',
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='static/main/img/news/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/main/img/users/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='RoleCourses',
        ),
    ]
