# Generated by Django 3.1.7 on 2021-05-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210520_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesBarista',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.course')),
            ],
        ),
    ]
