# Generated by Django 3.1.7 on 2021-05-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_course_modulesbarista'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesbarista',
            name='title',
            field=models.CharField(default='Title of module', max_length=100),
        ),
    ]
