# Generated by Django 3.1.7 on 2021-05-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_modulesbarista_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModulesBarista',
        ),
    ]
