# Generated by Django 3.1.7 on 2021-05-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_modulesbarista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title of module', max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Topic of lection', max_length=100)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.module')),
            ],
        ),
    ]
