# Generated by Django 3.1.7 on 2021-05-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_lection_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lection',
        ),
    ]
