# Generated by Django 3.2.3 on 2021-05-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='module_name',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
    ]
