# Generated by Django 3.2.3 on 2021-05-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210524_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Lection',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
