# Generated by Django 3.2.3 on 2021-05-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_module_order_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lection',
            old_name='module',
            new_name='parent',
        ),
    ]
