# Generated by Django 3.2.3 on 2021-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_module_lection_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='lection',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
