# Generated by Django 3.2.3 on 2021-06-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_lection_lection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='content',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='lection',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='lection',
            name='topic',
            field=models.CharField(default='Topic of lection', max_length=100, verbose_name='Заголовок'),
        ),
    ]
