# Generated by Django 3.1.7 on 2021-06-04 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210605_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lection',
            name='content',
        ),
        migrations.CreateModel(
            name='LectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='Содержание')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.module', verbose_name='Модуль')),
            ],
        ),
    ]
