# Generated by Django 3.1.7 on 2021-06-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210605_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectioncontent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.lection', verbose_name='Лекция'),
        ),
    ]
