# Generated by Django 3.1.7 on 2021-06-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210605_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='order_lection',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в модуле'),
        ),
    ]
