# Generated by Django 3.1.7 on 2021-06-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_lection_order_lection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lection',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='lectioncontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='module',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lection',
        ),
        migrations.DeleteModel(
            name='LectionContent',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
