# Generated by Django 3.2.4 on 2021-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_lection_order_lection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Ответ')),
                ('is_success', models.BooleanField(verbose_name='Правильность ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
                ('answers_id', models.JSONField(verbose_name='ID ответов')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('questions_id', models.JSONField(verbose_name='ID вопросов')),
            ],
        ),
    ]
