# Generated by Django 3.1.7 on 2021-06-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210616_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
