# Generated by Django 3.1.7 on 2021-06-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0038_auto_20210616_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('lection', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Topic of lection', max_length=100, verbose_name='Заголовок')),
                ('order_lection', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в модуле')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(default='Title of module', max_length=100, verbose_name='Название')),
                ('order_course', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в курсе')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='LectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='Содержание')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.lection', verbose_name='Лекция')),
            ],
        ),
        migrations.AddField(
            model_name='lection',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.module', verbose_name='Модуль'),
        ),
    ]
