# Generated by Django 3.1.7 on 2021-06-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectioncontent',
            options={'verbose_name': 'Контент лекции', 'verbose_name_plural': 'Контенты лекций'},
        ),
    ]
